//! UI <-> wire conversion for action plans (Phase 2 task 10).
//!
//! `MailOperation` (in `core::actions::operation`) and `ActionOutcome`
//! / `ActionError` are domain types - rich enums the action service
//! and UI handlers consume directly. The wire shapes (`WireMailOperation`,
//! `OperationResult`) are narrower, serializable mirrors that travel
//! over IPC.
//!
//! `to_wire_plan` and `to_wire_op` convert UI-side `ActionExecutionPlan`
//! / `MailOperation` into the wire form for `action.execute_plan`.
//! `wire_outcome_to_action_outcome` does the inverse for outcomes
//! arriving on the notification stream so the existing
//! `handle_action_completed` keeps working unchanged.
//!
//! Both directions use exhaustive `match` (no `_` wildcard) so adding
//! a `MailOperation` / `WireMailOperation` variant without updating
//! both sides is a compile error.

use service::actions::{ActionError, ActionOutcome, MailOperation, RemoteFailureKind};
use service_api::{
    ActionWireOperation, ActionWirePlan, OperationId, OperationResult, PlanId, RemoteFailure,
    WireFolderId, WireLabelGroupId, WireMailOperation, WireLabelId,
};
use types::{FolderId, LabelGroupId, LabelId};

use crate::action_resolve::ActionExecutionPlan;

/// Build an `ActionWirePlan` from a UI-side `ActionExecutionPlan`.
///
/// `plan_id` is generated by the caller (UUIDv7 via `PlanId::new_v7()`)
/// so the UI can stash completion metadata under that key before
/// sending the request.
///
/// Per-operation `operation_id` is the index into `plan.operations`
/// cast to `u32`. Plans never grow large enough to overflow `u32`,
/// and using the index keeps the `(plan_id, operation_id)` round-trip
/// straightforward when correlating `OperationOutcome` notifications
/// back to the originating slot.
pub fn to_wire_plan(plan_id: PlanId, plan: &ActionExecutionPlan) -> ActionWirePlan {
    let operations = plan
        .operations
        .iter()
        .enumerate()
        .map(|(idx, (account_id, thread_id, op))| ActionWireOperation {
            operation_id: OperationId(u32::try_from(idx).unwrap_or(u32::MAX)),
            account_id: account_id.clone(),
            thread_id: thread_id.clone(),
            operation: to_wire_op(op),
        })
        .collect();
    ActionWirePlan {
        plan_id,
        operations,
    }
}

/// Convert one `MailOperation` to its wire mirror.
pub fn to_wire_op(op: &MailOperation) -> WireMailOperation {
    match op {
        MailOperation::Archive => WireMailOperation::Archive,
        MailOperation::Trash => WireMailOperation::Trash,
        MailOperation::PermanentDelete => WireMailOperation::PermanentDelete,
        MailOperation::SetSpam { to } => WireMailOperation::SetSpam { to: *to },
        MailOperation::SetStarred { to } => WireMailOperation::SetStarred { to: *to },
        MailOperation::SetRead { to } => WireMailOperation::SetRead { to: *to },
        MailOperation::SetPinned { to } => WireMailOperation::SetPinned { to: *to },
        MailOperation::SetMuted { to } => WireMailOperation::SetMuted { to: *to },
        MailOperation::MoveToFolder { dest, source } => WireMailOperation::MoveToFolder {
            dest: folder_to_wire(dest),
            source: source.as_ref().map(folder_to_wire),
        },
        MailOperation::AddLabel { label_id } => WireMailOperation::AddLabel {
            label_id: label_to_wire(label_id),
        },
        MailOperation::RemoveLabel { label_id } => WireMailOperation::RemoveLabel {
            label_id: label_to_wire(label_id),
        },
        MailOperation::ApplyLabelGroup { group_id } => WireMailOperation::ApplyLabelGroup {
            group_id: label_group_to_wire(group_id),
        },
        MailOperation::RemoveLabelGroup { group_id } => WireMailOperation::RemoveLabelGroup {
            group_id: label_group_to_wire(group_id),
        },
        MailOperation::Snooze { until } => WireMailOperation::Snooze { until: *until },
        MailOperation::Unsnooze => WireMailOperation::Unsnooze,
    }
}

fn folder_to_wire(f: &FolderId) -> WireFolderId {
    WireFolderId(f.0.clone())
}

fn label_to_wire(t: &LabelId) -> WireLabelId {
    WireLabelId(t.0.clone())
}

fn label_group_to_wire(t: &LabelGroupId) -> WireLabelGroupId {
    WireLabelGroupId(t.0)
}

/// Reverse direction: turn a wire `OperationResult` into the
/// domain-shaped `ActionOutcome` the existing
/// `handle_action_completed` (and downstream toast / undo / rollback
/// logic) consumes.
///
/// **Note on lossiness.** The wire `OperationResult` does not
/// distinguish `NoOp` from `Success` - the worker maps both to
/// `Success` per `action_outcome_to_wire`. The existing handler's
/// `all_noop` short-circuit therefore won't fire for genuinely
/// no-op actions submitted via IPC; the action will surface as a
/// success even though no state changed. Phase 2 accepts this
/// regression; a `NoOp` wire variant can land later if the missing
/// short-circuit hurts UX.
pub fn wire_outcome_to_action_outcome(result: OperationResult) -> ActionOutcome {
    match result {
        OperationResult::Success => ActionOutcome::Success,
        OperationResult::LocalOnly => ActionOutcome::LocalOnly {
            reason: ActionError::remote("provider failure deferred to pending_ops"),
            // The wire form lost the retry classification; pending_ops
            // already has the entry queued for retry on the Service
            // side, so the UI-side `retryable` flag is purely
            // informational. Default to true (matches the
            // `LocalOnly` semantics: "deferred for later retry").
            retryable: true,
        },
        OperationResult::ConflictRejected { detail } => ActionOutcome::Failed {
            error: ActionError::not_found(detail),
        },
        OperationResult::RemoteFailure { failure } => ActionOutcome::Failed {
            error: ActionError::Remote {
                kind: classify_wire_remote(&failure),
                message: failure.provider_message,
            },
        },
    }
}

fn classify_wire_remote(failure: &RemoteFailure) -> RemoteFailureKind {
    if failure.retryable {
        RemoteFailureKind::Transient
    } else {
        RemoteFailureKind::Permanent
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn to_wire_op_round_trips_every_variant_through_serde() {
        // Exhaustive variant coverage; if a new MailOperation arm
        // lands without a wire mirror, this match (and `to_wire_op`)
        // fail to compile.
        let cases = [
            MailOperation::Archive,
            MailOperation::Trash,
            MailOperation::PermanentDelete,
            MailOperation::SetSpam { to: true },
            MailOperation::SetStarred { to: false },
            MailOperation::SetRead { to: true },
            MailOperation::SetPinned { to: false },
            MailOperation::SetMuted { to: true },
            MailOperation::MoveToFolder {
                dest: FolderId("inbox".into()),
                source: Some(FolderId("archive".into())),
            },
            MailOperation::AddLabel {
                label_id: LabelId("work".into()),
            },
            MailOperation::RemoveLabel {
                label_id: LabelId("personal".into()),
            },
            MailOperation::ApplyLabelGroup {
                group_id: LabelGroupId(7),
            },
            MailOperation::RemoveLabelGroup {
                group_id: LabelGroupId(7),
            },
            MailOperation::Snooze { until: 1_700_000_000 },
            MailOperation::Unsnooze,
        ];
        for op in cases {
            let wire = to_wire_op(&op);
            // Serde round-trip on the wire form keeps us honest about
            // the actual on-the-wire payload.
            let json = serde_json::to_value(&wire).expect("serialize");
            let recovered: WireMailOperation =
                serde_json::from_value(json).expect("deserialize");
            assert_eq!(wire, recovered);
        }
    }

    #[test]
    fn wire_outcome_success_maps_to_success() {
        let out = wire_outcome_to_action_outcome(OperationResult::Success);
        assert!(out.is_success());
    }

    #[test]
    fn wire_outcome_local_only_maps_to_local_only() {
        let out = wire_outcome_to_action_outcome(OperationResult::LocalOnly);
        assert!(out.is_local_only());
    }

    #[test]
    fn wire_outcome_conflict_maps_to_failed_not_found() {
        let out = wire_outcome_to_action_outcome(OperationResult::ConflictRejected {
            detail: "thread already archived".into(),
        });
        match out {
            ActionOutcome::Failed { error } => {
                let msg = error.user_message();
                assert!(msg.contains("already archived") || !msg.is_empty());
            }
            other => panic!("expected Failed, got {other:?}"),
        }
    }

    #[test]
    fn wire_outcome_remote_failure_carries_message() {
        let out = wire_outcome_to_action_outcome(OperationResult::RemoteFailure {
            failure: RemoteFailure {
                provider_message: "503 service unavailable".into(),
                http_status: Some(503),
                retryable: true,
            },
        });
        match out {
            ActionOutcome::Failed {
                error: ActionError::Remote { kind, message },
            } => {
                assert!(matches!(kind, RemoteFailureKind::Transient));
                assert!(message.contains("503"));
            }
            other => panic!("expected Failed::Remote, got {other:?}"),
        }
    }

    #[test]
    fn wire_outcome_remote_non_retryable_classifies_permanent() {
        let out = wire_outcome_to_action_outcome(OperationResult::RemoteFailure {
            failure: RemoteFailure {
                provider_message: "401 unauthorized".into(),
                http_status: Some(401),
                retryable: false,
            },
        });
        match out {
            ActionOutcome::Failed {
                error: ActionError::Remote { kind, .. },
            } => {
                assert!(matches!(kind, RemoteFailureKind::Permanent));
            }
            other => panic!("expected Failed::Remote, got {other:?}"),
        }
    }
}
