pub mod actions;
pub mod account;
pub use ratatoskr_stores::attachment_cache;
pub mod auto_responses;
pub mod bimi;
pub use ratatoskr_stores::body_store;
pub mod caldav;
pub mod carddav;
pub mod cloud_attachments;
pub mod contacts;
pub use ratatoskr_sync::categorization;
pub mod contact_photos;
pub use ratatoskr_label_colors::category_colors;
pub use ratatoskr_command_palette as command_palette;
pub mod db;
pub mod discovery;
pub mod email_actions;
pub mod generation;
pub use ratatoskr_sync::filters;
pub(crate) use ratatoskr_gmail as gmail;
pub(crate) use ratatoskr_graph as graph;
pub(crate) use ratatoskr_imap as imap;
pub use ratatoskr_label_colors as label_colors;
pub use ratatoskr_stores::inline_image_store;
pub(crate) use ratatoskr_jmap as jmap;
pub mod jmap_push;
pub mod mdn;
pub mod oauth;
pub use ratatoskr_db::progress;
pub mod provider;
pub mod scheduled_send;
pub mod scope;
pub mod send;
pub use ratatoskr_search as search;
pub mod search_pipeline;
pub use ratatoskr_smart_folder as smart_folder;
pub use ratatoskr_seen_addresses as seen_addresses;
pub mod send_identity;
pub use ratatoskr_sync::smart_labels;
pub use ratatoskr_smtp as smtp;
pub use ratatoskr_sync as sync;
pub use ratatoskr_sync::threading;
pub mod sync_dispatch;
pub mod url_cleaning;

// Re-exports for app-layer convenience — avoids direct provider-utils dependency.
pub use ratatoskr_provider_utils::crypto::load_encryption_key;
